<?php echo __("Featured Category"); ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $catId = 2;  //Parent Category ID
    $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
    $subCats = $subCategory->getChildrenCategories();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
   

?>
<ul class="sub-cat-ul">
    <?php
     $i=0;
    foreach ($subCats as $subcat) {
        $i++;
        if($i == 5){
            break;
        }
        $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
        $subcaturl = $subcat->getUrl();
        $_imgHtml = '';

        if ($_imgUrl = $_category->getImageUrl()) {
            $_imgHtml = '<img src="' .$this->getUrl().$_imgUrl . '" />';

             $_imgHtml;
             $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
            
        } ?>
        <li class="cat-li">
            <div class="cat-image">
                <a href="<?php echo $subcaturl ?>">
                    <?php echo $_imgHtml ?>
                        
                    </a>
            </div>
            <div class="info">
                <h4><?php echo $subcat->getName(); ?></h4>
                <a class="link" href="<?php echo $subcaturl ?>"><?php echo __('Explore Now') ?></a>
            </div>
        </li>

    <?php }
      ?>
</ul>