<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $catId = 2;  //Parent Category ID
    $subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
    $subCats = $subCategory->getChildrenCategories();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <div class="fetured_bg">
        <div class="container">
            <div class="featured_section">
                <div class="service_heading">
                    <h2>Featured Categories</h2>
                    <h3>Never be torn from one or the other again with the attractive WaterVue 19 inch waterproof bathroom TV.</h3>
                </div>

                    <div class="block_featured">
                        
                            <?php
                            $category_count = 1;
                            foreach ($subCats as $subcat) {
                                $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                                $subcaturl = $subcat->getUrl();
                                $_imgHtml = '';
                                if ($category_count < 5) {
                                 if ($_imgUrl = $_category->getImageUrl()) {
                                    $_imgHtml = '<img src="' .$this->getUrl().$_imgUrl . '" />';
                                    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
                                } ?>
                                <div class="category_block">
                                    
                                        <div class="product_img"><?php echo $_imgHtml;?>
                                        <div class="hover_block"><a class="link" href="<?php echo $subcaturl ?>"><?php /* @escapeNotVerified */ echo __('Explore now') ?></a>
                                        </div>
                                    </div>
                                    <h4><?php echo $subcat->getName(); ?></h4>
                              
                            </div>

                            <?php
                            $category_count++;
                        }   ?>
                    <?php } ?>
                </div>
            
        </div>
    </div>
</div>
